### ISSUE TITLE
Nodes are white out of box

### ISSUE THREAD

**Issue by ramentonkatsu** [brumenn/FlatNodes#4]
After installing plugin for UE5 and enabling it, nodes are all white and unreadable. Is there something I need to change?

![](https://i.gyazo.com/be9a16fd9db3b07d7c005a1ac0c470ff.png)

**Comment by brumenn** [comment]
What's your OS ? Are you on Windows ? Do you use any other styling plugin ?

**Comment by ramentonkatsu** [comment]
> What's your OS ? Are you on Windows ? Do you use any other styling plugin ?

OS is Windows 10 and I do not have another styling plugin. Also running Unreal Engine 5.0.1

**Comment by brumenn** [comment]
Have you got the same problem with the marketplace version ?

**Comment by douglaslassance** [comment]
I'm also having this in 4.27. I don't think it's 5 related.

**Comment by ramentonkatsu** [comment]
> Have you got the same problem with the marketplace version ?

I am using the marketplace version, I'll try the github version to see if that works.

**Comment by Metal-666** [comment]
I am facing the same problem (I'm using the marketplace version of the plugin)
Opened a project today - everything is fine
Closed, added a new plugin, removed a few I wasn't using, opened again
UI in blueprint editor is broken now
Tried removing the plugin from the engine and adding back - no difference

OS: Windows 11, Engine version: 5.0.1

**Comment by Metal-666** [comment]
Sooo I fixed the problem by adding back one of the plugins I removed - "Quixel Bridge". Is it required for FlatNodes to work?

**Comment by douglaslassance** [comment]
I'm getting the issue when cloning the GitHub code. It's worth noting that it does not happen all the time. If I restart the engine I might not get it. I did not figure out how to reproduce it accurately yet.

**Comment by ramentonkatsu** [comment]
> Sooo I fixed the problem by adding back one of the plugins I removed - "Quixel Bridge". Is it required for FlatNodes to work?

I did notice that Quixel Bridge was not installed on my engine before I reinstalled. Now it is and the plugin is working properly.

**Comment by brumenn** [comment]
That's weird, I see no reason why Quixel Bridge should be needed for FlatNodes to work. But cool if this could be a quick fix solution, I will investigate !

**Comment by Ares9323** [comment]
Is this really "fixed"?
I have quixel bridge installed and this happens randomly!

**Comment by brumenn** [comment]
Hi, can you tell me more infos about your engine version and where the plugin comes from ? thx

**Comment by Ares9323** [comment]
Hi, sure:
Plugin is from the Unreal Marketplace, it happens in both 4.27.2 and 5.0.3
As I said, it's kinda random, if I restart the editor sometimes the issue is fixed, sometimes it's not, I couldn't find a pattern to reproduce it.

**Comment by brumenn** [comment]
I need to update the plugin for 5.1, but it gonna be fine on my end I guess. Honestly, I'm not sure I will be able to reproduce the issue with my config, initially it was due to the fact that I wrote the plugin from a blank code and forgot some required lines like `FSlateApplication::Get().GetRenderer()->ReloadTextureResources();` but now it comes from the base template plugin of unreal and I don't see anything that I could have forgotten really ..
You are on windows right ?

**Comment by Ares9323** [comment]
Yes, Windows 11 22H2, formatted last week so it's a brand new installation (both Unreal and windows) and I used to have this issue on the previous install too.
