### ISSUE TITLE
[Animation blueprints] Transtion rule preview doesn't appear correctly

### ISSUE THREAD

**Issue by HotInnards** [brumenn/FlatNodes#9]
Hey brumenn, I noticed an issue with the plugin, specifically in animation blueprints in UE5.0.2. The transition rules between states show blank white instead of a preview of the variable name.

With plugin:
![Blank white](https://user-images.githubusercontent.com/6906325/171151584-0d7473c0-2386-496e-9181-afcfacaaf41a.png)

Without:
![Normal](https://user-images.githubusercontent.com/6906325/171152423-a10d1b8f-52e4-41b6-a2d8-6152a332093a.png)

**Comment by brumenn** [comment]
Thanks for your report, I'll check that !

**Comment by brumenn** [comment]
Fixed with #8 in 9972554b834fc322ebbfe0eba11dd805a9bb093f
